# Generated by Django 4.2.16 on 2024-10-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_product_image_sellerproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerproduct",
            name="image",
            field=models.ImageField(default=None, upload_to="seller_products"),
        ),
    ]
