# Generated by Django 5.1 on 2024-10-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('addres', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('paytype', models.CharField(max_length=100)),
            ],
        ),
    ]
