# Generated by Django 4.2.16 on 2024-10-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_tracking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment", old_name="addres", new_name="address",
        ),
    ]
