# Generated by Django 4.2.16 on 2024-10-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_rename_addres_payment_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
