# Generated by Django 4.2.16 on 2024-10-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_profile_username"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="username",),
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
