# Generated by Django 5.0.6 on 2024-10-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_profile_username_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
